---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Express Application/API powered by API Gateway and Lambda

Resources:

  BlueCoatGoogleOAuthRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: execute-api:Invoke
            Resource: !Join
              - ''
              - - 'arn:aws:execute-api:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - !Ref BlueCoatRestApi
                - "/*/*"
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated: accounts.google.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              accounts.google.com:aud: 953648658436-1bql4k0mhfaiqe8p141c4rs0sgsjbcut.apps.googleusercontent.com
      RoleName: "BlueCoatGoogleOAuthRole"




  BlueCoatTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "bluecoat"
      TimeToLiveSpecification:
        AttributeName : "TTL"
        Enabled : false
      AttributeDefinitions: 
        - 
          AttributeName: "recordType"
          AttributeType: "S"
        - 
          AttributeName: "identifier"
          AttributeType: "S"
        - 
          AttributeName: "record"
          AttributeType: "N"
        - 
          AttributeName: "TTL"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "recordType"
          KeyType: "HASH"
        - 
          AttributeName: "identifier"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      GlobalSecondaryIndexes: 
        - 
          IndexName: "index"
          KeySchema: 
            - 
              AttributeName: "recordType"
              KeyType: "HASH"
            - 
              AttributeName: "record"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
      StreamSpecification: 
        StreamViewType: "NEW_IMAGE"

  BlueCoatRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "BlueCoatRestApi"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./proxy-api.yaml
      StageName: prod

  APIHandlerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            Resource: !Join
              - '' 
              - - 'arn:aws:dynamodb:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - "table/bluecoat"
          - Effect: Allow
            Action:
            - dynamodb:Query
            Resource: !Join
              - '' 
              - - 'arn:aws:dynamodb:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - "table/bluecoat/index/index"

  BlueCoatRestApiGatewayExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt RestAPIHandler.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref BlueCoatRestApi
          - "/*/*"

  RestAPIHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: restHandler/
      Handler: lambda.handler
      MemorySize: 1024
      Role: !GetAtt APIHandlerExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref BlueCoatRestApi
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref BlueCoatRestApi
            Path: /{proxy+}
            Method: ANY

  StreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: streamProcessor/
      Handler: lambda.handler
      MemorySize: 1024
      Role: !GetAtt StreamProcessorExecutionRole.Arn
      Runtime: nodejs12.x
      Timeout: 30
      Events:

  StreamProcessorExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:DescribeStream
            - dynamodb:ListStreams
            Resource: !Join
              - '' 
              - - 'arn:aws:dynamodb:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - "table/bluecoat/*"
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            Resource: !Join
              - '' 
              - - 'arn:aws:dynamodb:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - "table/bluecoat"

  StreamProcessorTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties: 
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt BlueCoatTable.StreamArn
      FunctionName: !GetAtt StreamProcessor.Arn
      MaximumBatchingWindowInSeconds: 0
      MaximumRecordAgeInSeconds: 60
      MaximumRetryAttempts: 3
      ParallelizationFactor: 3
      StartingPosition: LATEST


  BlueCoatSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      Description: "Blue Coat Socket API"
      DisableSchemaValidation: true
      Name: "BlueCoatSocketApi"
      ProtocolType: "WEBSOCKET"
      RouteSelectionExpression: "$request.body.action"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BlueCoatSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BlueCoatSocketApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SocketHandler.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BlueCoatSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BlueCoatSocketApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SocketHandler.Arn}/invocations
  PingRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref BlueCoatSocketApi
      RouteKey: ping
      AuthorizationType: NONE
      OperationName: PingRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref PingInteg
  PingInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref BlueCoatSocketApi
      Description: Ping Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SocketHandler.Arn}/invocations

  SocketHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./socketHandler
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs12.x
      Role: !GetAtt SocketHandlerExecutionRole.Arn
      Environment:
        Variables:
          ENDPOINT: !Join
                - ''
                - - https://
                  - !Ref BlueCoatSocketApi
                  - ".execute-api."
                  - !Ref AWS::Region
                  - ".amazonaws.com/prod/"

  SocketHandlerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - execute-api:ManageConnections
            Resource: !Join
              - '' 
              - - 'arn:aws:execute-api:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - !Ref BlueCoatSocketApi
                - "/prod/*"
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:DescribeStream
            - dynamodb:ListStreams
            Resource: !Join
              - '' 
              - - 'arn:aws:dynamodb:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - "table/bluecoat/*"
          - Effect: Allow
            Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            Resource: !Join
              - '' 
              - - 'arn:aws:dynamodb:'
                - !Ref AWS::Region
                - ":"
                - !Ref AWS::AccountId
                - ":"
                - "table/bluecoat"

  SocketExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SocketHandler.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref BlueCoatSocketApi
          - "/*/*"
  
  SocketHandlerChangeTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties: 
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt BlueCoatTable.StreamArn
      FunctionName: !GetAtt SocketHandler.Arn
      MaximumBatchingWindowInSeconds: 0
      MaximumRecordAgeInSeconds: 60
      MaximumRetryAttempts: 3
      ParallelizationFactor: 3
      StartingPosition: LATEST

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - DisconnectRoute
    - PingRoute
    Properties:
      ApiId: !Ref BlueCoatSocketApi
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      DeploymentId: !Ref Deployment
      ApiId: !Ref BlueCoatSocketApi



Outputs:
  LambdaFunctionConsoleUrl:
    Description: Console URL for the Lambda Function.
    Value: !Join
      - ''
      - - https://
        - !Ref AWS::Region
        - ".console.aws.amazon.com/lambda/home?region="
        - !Ref AWS::Region
        - "#/functions/"
        - !Ref RestAPIHandler

  ApiGatewayApiConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value: !Join
      - ''
      - - https://
        - !Ref AWS::Region
        - ".console.aws.amazon.com/apigateway/home?region="
        - !Ref AWS::Region
        - "#/apis/"
        - !Ref BlueCoatRestApi
        - "/stages/prod"

  ApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Join
      - ''
      - - https://
        - !Ref BlueCoatRestApi
        - ".execute-api."
        - !Ref AWS::Region
        - ".amazonaws.com/prod/"
